# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a', '0002_auto_20170625_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='b',
            name='charfield',
            field=models.CharField(db_index=True, default='', max_length=1),
        ),
        migrations.AddField(
            model_name='b',
            name='intfield',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
